### ISSUE TITLE
State on which HTTP messages the header field values can appear

### ISSUE THREAD

**Issue by LPardue** [tus/tus-v2#16]
_This seems a bit up in the air so I held of on a PR._ 

Which endpoint can send the new header fields is implied but not stated explicity. We can be clearer by stating it like "request header field" for client-only headers, "response header field" for server-only headers, or "request and response header field" if it can be used by both.

**Comment by guoye-zhang** [comment]
`Upload-Token` is "request header field", `Upload-Offset` and `Upload-Incomplete` are both "request and response header field".
