### ISSUE TITLE
Confusing use of Content-Disposition

### ISSUE THREAD

**Issue by LPardue** [tus/tus-v2#24]
https://tus.github.io/tus-v2/draft-tus-resumable-uploads-protocol.html#section-4-8 currently says:

> The client MAY send the metadata of the file using headers such as Content-Type (see Section 8.3 of [HTTP] and Content-Disposition [RFC6266] when starting a new upload. It is OPTIONAL for the client to repeat the metadata when resuming an upload.

There's a PR that tweaks the text but it still leaves content-disposition there, which I find confusing because [RFC6266](https://datatracker.ietf.org/doc/html/rfc6266) states that Content-Disposition is a response header (not a request one), We shouldn't be offhandledly recommending breaking HTTP semantic rules. If use of Content-Disposition on requests is a valuable feature for resumable uploads, we probably need to pursue that with more detail.

**Comment by Acconut** [comment]
Addressed in https://github.com/tus/tus-v2/pull/35
