### ISSUE TITLE
Ambiguous paragraph in Upload Transfer Procedure

### ISSUE THREAD

**Issue by nhedger** [tus/tus-v2#48]
While reading the `Upload Transfer Procedure`, I found the following paragraph ambiguous.

[Section 4-4](https://tus.github.io/tus-v2/draft-tus-httpbis-resumable-uploads-protocol.html#section-4-4)
> The request MUST include the Upload-Token header field ([Section 7.1](https://tus.github.io/tus-v2/draft-tus-httpbis-resumable-uploads-protocol.html#upload-token)) which uniquely identifies an upload. The client MUST NOT reuse the token for a different upload.

While it correctly states that the `Upload-Token` MUST be included, it does not say what the server's response should be in that case. I could not find anywhere else in the document instructions for handling this case. Is this by design or did I miss anything ?

1. If the `Upload-Token` is always required (which the paragraph suggests), I would probably expect the server to reject the request with status `400`.
2. If the `Upload-Token` is not always required, perhaps to allow the same `[http verb, endpoint]` combo to be used differently than for a file upload, it might be useful to explicitly state it.

Cheers.

**Comment by guoye-zhang** [comment]
Good point. Will clarify in the next draft.

The intention is to allow a regular upload to be upgraded to a resumable upload, so the server should usually support both on the same endpoint. Missing `Upload-Token` means the upload isn't resumable.
