### ISSUE TITLE
discussion: Upload-Token cryptographic strength suggestion

### ISSUE THREAD

**Issue by justinruggles** [tus/tus-v2#5]
current wording:
```
The value of the token SHOULD be a byte sequence
with a minimum of 256-bit (16 byte) cryptographically-secure
random binary data, or a cryptographic token with equivalent
or stronger security properties.
```

1. There is a typo. Either it's 256-bit (32 byte) or 128-bit (16-byte).
2. I think we should discuss the value in giving a specific recommendation

I think the real goal is that the Upload-Token should contain or encapsulate an identifier that applies to a single upload and is sufficiently unique to the upload server system. One alternative to having the `SHOULD` with specific requirements could be to give a MUST for system-dependent uniqueness and a 128-bit cryptographically random byte sequence as one example.

**Comment by Acconut** [comment]
This sentencing was improved by https://github.com/tus/tus-v2/pull/7
