### ISSUE TITLE
Add note about not supporting parallel chunked uploads

### ISSUE THREAD

**Issue by guoye-zhang** [tus/tus-v2#51]
Add note about not supporting parallel chunked uploads.

It's brought up because resumable download supports parallel chunked downloads but we have no intention to support parallel chunked uploads.

**Comment by gregw** [comment]
This is made clear in [section 6](https://datatracker.ietf.org/doc/html/draft-tus-httpbis-resumable-uploads-protocol-01#section-6) but a note in the intro saying that it is so (and different to range requests) might be a nice-to-have.
