### ISSUE TITLE
Can server skip ahead?

### ISSUE THREAD

**Issue by guoye-zhang** [tus/tus-v2#52]
Can server skip ahead using Offset Retrieving Procedure? Current thinking is there is no harm in allowing it.

**Comment by gregw** [comment]
I also see no harm in skipping forward.  

But once it has done so, can it skip back to any gap in the bytes?  ie must the offset generated by the server be monotonically increasing?

I think it is OK to send an offset less that a previous one, so long as #53 requires that any resumed bytes are identical to what was originally sent (or would have been sent).

**Comment by Acconut** [comment]
Personally I would vote against allow this. I do not really see a use case but it would require more complexity in the client implementations. I like to understand resumable uploads as append-only files. Each transferred chunk simply added to the end of the current upload. With this context, my answers for the other questions would be:

> can it skip back to any gap in the bytes?

No. 

> ie must the offset generated by the server be monotonically increasing?

Yes. This guarantee of monotonically increasing offsets can allow for great reduction of complexity for clients and server compared to when client and server must handle basically arbitrary offsets.
